In [1]:
import pandas as pd

In [2]:
spl_df = pd.read_csv("https://seattle-library-checkout-data.s3.us-west-2.amazonaws.com/norton-anthology_spl-checkouts_2005-2025.csv")

/var/folders/06/y6vmvyfj0wg08vb3rszcfy080000gn/T/ipykernel_12997/3367337367.py:1: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  spl_df = pd.read_csv("https://seattle-library-checkout-data.s3.us-west-2.amazonaws.com/norton-anthology_spl-checkouts_2005-2025.csv")

In [3]:
spl_df.head()

,Unnamed: 0,UsageClass,CheckoutOutType,MaterialType,CheckoutYear,CheckoutMonth,Checkouts,Title,Creator,Subjects,Publisher,PublicationYear,ISBN,Normalized.Creator,Normalized.Title,BirthYear,DeathYear,Work.In.Norton
0,0,Digital,OverDrive,AUDIOBOOK,2016,10,1,The Natural (Unabridged),Bernard Malamud,"Classic Literature, Fiction","Blackstone Audio, Inc.",2008,NaN,Bernard Malamud,The Natural,1914,1986.0,False
1,1,Digital,OverDrive,EBOOK,2016,10,1,The Assistant,Bernard Malamud,"Fiction, Literature",Macmillan Publishers,2013,NaN,Bernard Malamud,The Assistant,1914,1986.0,False
2,2,Digital,OverDrive,EBOOK,2016,11,1,The Magic Barrel,Bernard Malamud,"Fiction, Literature",Macmillan Publishers,2013,NaN,Bernard Malamud,The Magic Barrel,1914,1986.0,True
3,3,Digital,OverDrive,EBOOK,2016,11,1,The Assistant,Bernard Malamud,"Fiction, Literature",Macmillan Publishers,2013,NaN,Bernard Malamud,The Assistant,1914,1986.0,False
4,4,Digital,OverDrive,EBOOK,2016,12,1,The Fixer: A Novel,Bernard Malamud,"Fiction, Literature",Macmillan Publishers,2013,NaN,Bernard Malamud,The Fixer,1914,1986.0,False

In [4]:
spl_df["CheckoutDate"] = pd.to_datetime(
    dict(year=spl_df["CheckoutYear"], month=spl_df["CheckoutMonth"], day=1)
)

In [20]:
author_checkouts_per_month = spl_df.groupby(['Normalized.Creator', 'CheckoutDate', 'Work.In.Norton'])['Checkouts'].sum().reset_index()

In [24]:
title_checkouts_per_month = spl_df.groupby(['Normalized.Title', 'Normalized.Creator',  'Work.In.Norton','CheckoutDate'])['Checkouts'].sum().reset_index()

In [25]:
title_checkouts_per_month

,Normalized.Title,Normalized.Creator,Work.In.Norton,CheckoutDate,Checkouts
0,"""All Labor Has Dignity""",Martin Luther King Jr.,False,2011-02-01,2
1,"""All Labor Has Dignity""",Martin Luther King Jr.,False,2011-09-01,1
2,"""All Labor Has Dignity""",Martin Luther King Jr.,False,2012-01-01,1
3,"""All Labor Has Dignity""",Martin Luther King Jr.,False,2012-02-01,1
4,"""All Labor Has Dignity""",Martin Luther King Jr.,False,2012-03-01,1
...,...,...,...,...,...
138926,Zuckerman Unbound,Philip Roth,False,2025-02-01,1
138927,Zuckerman Unbound,Philip Roth,False,2025-03-01,1
138928,Zuckerman Unbound,Philip Roth,False,2025-04-01,1
138929,Zuckerman Unbound,Philip Roth,False,2025-05-01,2
138930,Zuckerman Unbound,Philip Roth,False,2025-06-01,4

In [31]:
title_checkouts_per_month.to_csv("title-checkouts-per-month.csv", index = False)

In [28]:
aggregated_checkouts_title_authors = title_checkouts_per_month.groupby(['Normalized.Title', 'Normalized.Creator', 'Work.In.Norton'])['Checkouts'].sum().sort_values( ascending=False).reset_index()

In [29]:
aggregated_checkouts_title_authors

          Normalized.Title Normalized.Creator  Work.In.Norton  Checkouts
0     Parable Of The Sower  Octavia E. Butler           False      21652
1     Lincoln In The Bardo    George Saunders           False      17356
2         The Fifth Season      N. K. Jemisin           False      17223
3          The Sympathizer  Viet Thanh Nguyen           False      12792
4                  Kindred  Octavia E. Butler           False      12591
...                    ...                ...             ...        ...
1643          Wise Whys Ys       Amiri Baraka           False          1
1644            Footprints    Denise Levertov           False          1
1645      Walking To Sleep     Richard Wilbur           False          1
1646             Aloneness   Gwendolyn Brooks           False          1
1647          Spirit Reach       Amiri Baraka           False          1

[1648 rows x 4 columns]

In [30]:
aggregated_checkouts_title_authors.to_csv("aggregated-checkouts-title-authors.csv", index=False)